name: pkgcheck

on:
  push:
    branches: [master,github]
  pull_request:
    branches: [master,github]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@dev
